### PR TITLE
rn-47: Mention JGit and Gerrit security vulnerabilities

### PR DESCRIPTION
**Pull request by dpursehouse**

### CODE REVIEW

**Comment by chriscool** [comment]
Do you have links so that interested people can take adeeper look?

**Comment by dpursehouse** [comment]
There were no bug reports on jgit, only on gerrit. I can add links to
those, but they don't say much more than what I added here and what is
mentioned in the gerrit/jgit release notes that are already linked.

All the discussions around the bugs were done on the gerrit maintainers
mailing list which is not public.

**Comment by chriscool** [comment]
I think it's still better to add the links even if they don't say much more.

**Comment by dpursehouse** [comment]
@chriscool I've added another commit with the links.

**Comment by chriscool** [comment]
Great! Thanks!

**Pull request merged**
