### PR TITLE
Edition 95: update Developer Spotlight

### PR DESCRIPTION
**Pull request by dyrone**

### CODE REVIEW

**Comment by dyrone** [comment]
Hi @mjaix 

I posted a PR on this, maybe it's easier to review.

Thanks.

**Comment by chriscool** [comment]
The change related to "patchsets" was made by @mjaix in https://github.com/git/git.github.io/commit/0da11543e1aeef76038b5f44cfb47c11cab92b41 as it seems that "patch sets" is more correct English wise.

Anyway I am going to merge this.

**Comment by chriscool** [comment]
@sivaraam and @mjaix your opinion on this is welcome.

I am Ok with tweaking the result a bit more even at this late stage.

**Comment by sivaraam** [comment]
This looks good. I just did some very minor tweaks in 8dde4ff9d5156c9d4745ba4318788050af8354b3.

**Comment by mjaix** [comment]
It looks OK to me. Gerrit uses "patch set", but "patchset" seems to be used even more according to Google hit counts.
Personally, I would prefer "patch set", but I am not pedantic :-).

**Pull request merged**
