### PR TITLE
rn20: expand a but about Dscho's work on interactive rebase

### PR DESCRIPTION
**Pull request by jnareb**
Add an information from Dscho about the use of Scientist library to ensure that the patches making interactive rebase faster are in fact correct.

I'm not sure if the new information is well connected to the rest of it; as it is now, this point has actually two endings...

### CODE REVIEW

**Comment by chriscool** [comment]
@jnareb I think this could go into a short separate article just below the existing one on rebase -i.
Are you ok to change it into an article?

**Comment by jnareb** [comment]
@chriscool I don't mind changing it into a (short) article. 

This would solve the problem of two endings ;-)

**Comment by chriscool** [comment]
Ok I will do that then.

**Comment by chriscool** [comment]
See https://github.com/git/git.github.io/commit/23f9abea01a9fd97b6f0904795cf20c9a6598592

**Pull request merged**
