### PR TITLE
Add some rambling/highlight about the GerritSummit

### PR DESCRIPTION
**Pull request by stefanbeller**

### CODE REVIEW

**Comment by stefanbeller** [comment]
The Gerrit summit was held in Mountain View, though I think not many pure Git topics were discussed. See https://gerrit.googlesource.com/summit/2015/+/HEAD/sat.md for more information.

**Comment by tfnico** [comment]
Thanks, Stefan!

**Comment by chriscool** [comment]
Yeah, thanks Stefan!
Maybe we could add a link to the Gerrit Summit and also the dates when it happened.
I will create a PR.

**Comment by chriscool** [comment]
I ended up pushing https://github.com/git/git.github.io/commit/09df83c4af634b704a98a2e61f17e9b4854ebd1d. I hope it is ok for you!

**Pull request merged**
