### PR TITLE
Easy watching: A Git Flow visualisation link

### PR DESCRIPTION
**Pull request by PhilipOakley**
An interesting use of a DAG based visualisation tool to show the Git Flow method.

Signed-off-by: Philip Oakley <philipoakley@iee.email>

### CODE REVIEW

**Comment by chriscool** [comment]
@PhilipOakley sorry I just saw this PR while I am in the process of publishing edition 93. Would it be Ok if we add this link to the next edition? Thanks anyway!

**Comment by PhilipOakley** [comment]
> just saw this PR while I am in the process of publishing edition 93. Would it be Ok if we add this link to the next edition?

Yes, that's fine. 
Thanks for your continued efforts on keeping the Rev News flowing!

**Comment by chriscool** [comment]
Rebased and then merged in d889cb2.

**Comment by chriscool** [comment]
The rebase unfortunately means that GitHub doesn't see this as merged. Sorry!

**Pull request closed without merging**
