### PR TITLE
README: discourage Git bug reporting

### PR DESCRIPTION
**Pull request by chriscool**
Let's try to avoid people using issues in this repo to discuss/report Git problems.

### CODE REVIEW

**Comment by peff** [comment]
We've had some success in git-scm repository with using templates. E.g., try https://github.com/git/git-scm.com/issues/new/choose, which is driven by the files in https://github.com/git/git-scm.com/tree/main/.github/ISSUE_TEMPLATE. It's not perfect, of course, but at least it puts the information in front of people right when they're trying to open the issue.

**Comment by chriscool** [comment]
@peff Yeah, that's a good idea! Thanks for the links!

**Review by sivaraam — APPROVED** [review]
The changes here look good. But after seeing the issue template suggestion which seems like a much better solution to the problem. I wonder if we want to do this 🤔

**Comment by chriscool** [comment]
@sivaraam let's merge this now and try to do the issue template suggestion soon. We can revisit this after the issue template has been improved.

**Pull request merged**
