### PR TITLE
Created CODE_OF_CONDUCT

### PR DESCRIPTION
**Pull request by jivthesh**

### CODE REVIEW

**Comment by peff** [comment]
How does this differ from #449?

**Comment by jivthesh** [comment]
@peff I have closed that

**Comment by sivaraam** [comment]
I believe @peff's concern is still left unanswered:

> Since this repo is really an extension of the Git project, would it make sense to use the CoC from git.git?

**Comment by jivthesh** [comment]
@peff @sivaraam may be

**Review by fahad3344 — APPROVED** [review]

**Comment by fahad3344** [comment]
> ج

**Comment by sivaraam** [comment]
Closing this due to lack of progress. Feel free to open another with the proposed changes :)

**Pull request closed without merging**
