### PR TITLE
rn-105: minor copy edit

### PR DESCRIPTION
**Pull request by stepnem**
(BTW, most likely I would have reviewed rn104, too, but
apparently you didn't send the usual Draft mail last month.)

### CODE REVIEW

**Comment by chriscool** [comment]
Thanks @stepnem ! I don't have much time today to take a look, but maybe @mjaix as he usually works on small fixes will be able to take a look. Otherwise I will take a look tomorrow.

About the Draft for last month, you are right, I made a mistake. Instead of putting a lot of people in Cc: I put them in the To: field and forgot to add the mailing list email address to the To:. So the mailing list didn't receive it as usual. Sorry about this. This shouldn't happen again, but if you want I can always put you in Cc:.

You would also be welcome to join the team, so that you could modify the master branch directly.

**Review by mjaix — APPROVED** [review]
IMHO just an excellent contribution.

**Comment by mjaix** [comment]
***@***.***,
I just merged your contribution - IMHO just excellent. Thanks a lot.
@chriscool: Is it OK for you if I proceed with looking for small fixes
this evening latest before 22:00?

**Comment by mjaix** [comment]
** sent again from the appropriate email address **

Great - I also would have preferred to use Štěpán's full name, but
failed to look it up :-(.

**Pull request merged**
