### PR TITLE
Add light reading link: Git before GitHub

### PR DESCRIPTION
**Pull request by tarunbatra**

### CODE REVIEW

**Comment by chriscool** [comment]
Please add the entry in the `__Light reading__` section of the file, instead of under "Developer Spotlight".

Another improvement could be to change the commit and pull request title to something like "rn-69: add 'Git before GitHub' article to Light reading section".

Thanks!

**Comment by tarunbatra** [comment]
Ah my bad. Thanks for reviewing. Fixed the commit.

**Comment by chriscool** [comment]
Merged! Thanks!

**Comment by sivaraam** [comment]
Curiously, the article referenced by the entry being added appears to be found here: https://tarunbatra.com/blog/x/git-before-github/

So, wouldn't it be more appropriate to link to it instead of linking to the associated repository? 🤔

**Comment by tarunbatra** [comment]
That's correct, @sivaraam. I meant to add the blog, but added the link to git repository by mistake.

Fixed it in PR #466. Thanks!

**Pull request merged**
