### PR TITLE
SoC: use 'criticizing' instead of 'critiquing'

### PR DESCRIPTION
**Pull request by chriscool**
It seems to me that 'critiquing' is not correct.

cc @peff @moy

### CODE REVIEW

**Comment by moy** [comment]
It seems it is actually correct actually:
http://public.wsu.edu/~brians/errors/critique.html
http://www.wordreference.com/enfr/critique

But I'll let native speakers decide ;-).

**Comment by chriscool** [comment]
Yeah it is strange that there is also criticize: http://www.wordreference.com/enfr/criticize

**Comment by peff** [comment]
I think "criticize" was the original verb, but like many things, we Americans managed to start using the noun form as a verb. These days, though, I think I would prefer "critique"; it implies a constructive objectiveness to the feedback, whereas "criticize" generally implies strict negativity. I have no idea if that is different in British English, though.

**Comment by chriscool** [comment]
Ok, let's just keep "critiquing" then.

**Comment by fugazyrappersoutlook** [comment]
https://github.com/MichaelAquilina/Reddit-Data/pull/3

**Pull request closed without merging**
