### PR TITLE
Gather some ideas on how to produce content

### PR DESCRIPTION
**Pull request by tfnico**
Just for starters.

### CODE REVIEW

**Comment by tfnico** [comment]
ping @chriscool :)

**Comment by chriscool** [comment]
By the way @tfnico are you ok with the name "Git Rev News" or do you prefer something else?

**Comment by tfnico** [comment]
@chriscool Hmm, I personally liked Git Praise the most. It's fairly unique and fresh. I think Git Rev News competes wit "git rev" on Internet search engines, and git-review is already taken by that Gerrit command. Git Grapevine is another one I just came up with.

**Comment by tfnico** [comment]
@chriscool By the way, I'm fine with "Git Rev News" too. The important thing is to Ship It (tm) :)

**Comment by chriscool** [comment]
@tfnico Yeah I agree. I will start gathering and writing some content soon.

**Comment by tfnico** [comment]
@chriscool OK. Do you think we should create a distinct repo for this (news), or should we start creating issues in here?

**Comment by chriscool** [comment]
@tfnico I'd rather start with this repo and do something only if people complain.

**Comment by tfnico** [comment]
Sounds good!

**Pull request merged**
