### PR TITLE
Make Beginner Application commads For Beginners easy to use git.

### PR DESCRIPTION
**Pull request by Muhammad-Awab**
Changes to css make shorthand property || Add Beginner_Application_Git_Commands.md file for beginners for easy to use git.

### CODE REVIEW

**Comment by chriscool** [comment]
It seems to me that the commit in this PR wants to do too many things and the PR doesn't explain why it should all be in the same commit.

Please try to explain clearly in the PR and in each commit message why each change is made, especially what would improve for the reader and why it is a good thing.

About adding Beginner_Application_Git_Commands.md I am not sure it is a good idea to start a new kind of tutorial here. Please read what we say at the top of https://git.github.io/Hacking-Git/. Please also note that `git help` already provides a short list of command and it's better to suggest starting using git help as it allows users to easily get more information about specific commands or topics. It also has a glossary and many features.

**Comment by Muhammad-Awab** [comment]
I wanted to add collaborator in this repo. How can I do this.

**Comment by chriscool** [comment]
> I wanted to add collaborator in this repo. How can I do this.

Why do you want that? We will only add collaborators who have helped the Git project for some time. (Also you should ask for that in a separate issue.)

**Comment by Muhammad-Awab** [comment]
Yes I wanted to help you to make git project. I am full stack developer.

**Comment by Muhammad-Awab** [comment]
GIve me some work I will complete this.

**Comment by chriscool** [comment]
> Yes I wanted to help you to make git project. I am full stack developer.
> GIve me some work I will complete this.

This project is about the Git Developer Pages at https://git.github.io/ and the Git Rev News newsletter. If you want to contribute to these pages or the newsletter, please take a look at the open issues: https://github.com/git/git.github.io/issues/ You can alternatively open new issues if you have other suggestions about how we could improve.

If you are interested in contributing to Git itself, then https://git.github.io/General-Microproject-Information/ and https://git.github.io/Hacking-Git/ might help you get started.

**Comment by Muhammad-Awab** [comment]
Thank you

**Comment by chriscool** [comment]
For example if you want to help us resolve this issue: https://github.com/git/git.github.io/issues/561

You might want to take a look at https://git.github.io/SoC-2023-Ideas/ and check that each project idea on that page has the following items:



a) a project title/description
b) more detailed description of the project (2-5+ sentences)
c) expected outcomes
d) skills required/preferred
e) possible mentors
f) expected size of project (175 or 350 hour)
g) an easy, medium or hard difficulty rating of each project.

**Comment by chriscool** [comment]
I am going to close this as I think adding `Beginner_Application_Git_Commands.md` is not a good idea (see https://github.com/git/git.github.io/pull/634#issuecomment-1479031806).

**Pull request closed without merging**
