### PR TITLE
revnews: mention some recent releases

### PR DESCRIPTION
**Pull request by tfnico**
I figure it is interesting to mention recent Git "core" releases, 
as well as in related projects (libgit2, jgit, etc).

PR for @chriscool, since it is a larger block of text.

### CODE REVIEW

**Comment by chriscool** [comment]
@tfnico ok, but then "Commandline GUI-tool tig version 1.2 was released." could be moved in the release section too?

**Comment by chriscool** [comment]
By the way, maybe we could use "Media" or "Other" instead of "From outside the list". I think it would be simpler and more inline with the other section titles.

**Comment by tfnico** [comment]
@chriscool Sorry for not responding earlier. +1 on all points. Thanks.

**Comment by chriscool** [comment]
Ok, thanks for responding.

As you can see, I added a patch to move the tig news into the Releases to this PR and I merged it before publishing edition 1.

About using "Media" or "Other" instead of "From outside the list", I will let's say use "Other" in edition 2.

**Pull request merged**
