### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by snxx-lppxx**

### CODE REVIEW

**Comment by chriscool** [comment]
Yeah, this might improve things a bit. Let's try it!

**Comment by chriscool** [comment]
Actually it doesn't seem to work. Not sure why. I am on Firefox.

**Comment by sivaraam** [comment]
Git and Git's logo is [a trademark](https://www.git-scm.com/about/trademark). I'm not sure but is it really fine for us to use the logo as a favicon for the Git Developer Pages site which is primarily a home for Git Rev News? It's likely that it might be fine but I'm just curious to know for sure.

**Comment by chriscool** [comment]
@sivaraam we are part of the Git community and part of the Git project, so we have the right to do it. When we send editions via email, we even put the SFConservancy's address at the bottom of the email:

Software Freedom Conservancy - Git Project
137 Montague ST STE 380
New York, NY 11201

And Junio talks about us in his "A note from the maintainer":

"There is a volunteer-run newsletter to serve our community ("Git Rev
News" http://git.github.io/rev_news/)."

We are also in the "Newsletter" section on https://git-scm.com/community:

"There is a monthly community newsletter called "Git Rev News", with its archive and its latest edition. Information on how to subscribe can be found on the dedicated webpage."

**Comment by sivaraam** [comment]
@chriscool Thanks for the detailed information! I think we could give #494 a try. I verified it locally and it seems to show the logo properly as a favicon for me.

Also, I came across the following QA which seems to suggest a syntax as used in that PR: https://stackoverflow.com/questions/30551501/unable-to-set-favicon-using-jekyll-and-github-pages

**Comment by peff** [comment]
> we are part of the Git community and part of the Git project, so we have the right to do it

Yeah, just adding a "me too" that I also agree that RevNews (and all the project stuff that happens via the git.github.io pages) is representing the project and OK to use the name, logo, etc. For the curious, if there were any doubt here, the place to ask would be Git's Project Leadership Committee (the community folks that represent the project within Software Freedom Conservancy), which could say "yes, this is part of the project" or "no, please stop using the name, etc".

But IMHO there isn't really any doubt here (and also, @chriscool and I are 2/4 of the members of that committee :wink:).

**Comment by gitster** [comment]
methree.

**Pull request merged**
