### PR TITLE
SoC-2020-Ideas.md: add trailing empty lines to force rebuild

### PR DESCRIPTION
**Pull request by jnareb**
Unfortunately the commit 6b5edec6557930888441c626f9272dc2be0c769e failed to build.

> The page build failed for the `master` branch with the following error:
>
> Unable to build page. Please try again later.

This pull request was created to examine, and if possible fix this issue.

### CODE REVIEW

**Comment by sivaraam** [comment]
@jnareb That's interesting. Where did you check that the build has failed? 🤔 

I thought I'll find the build status near the commit but the status could be found only for 5e72f5a296747b2e3c58b872980c66f302f7cfd0 and not for 6b5edec6557930888441c626f9272dc2be0c769e. I also tried searching other placed but couldn't find the failed build status for that commit.

**Comment by jnareb** [comment]
@sivaraam : I got an email from GitHub about the failed build, and as you can check the current contents of the <https://git.github.io/SoC-2020-Ideas/> page does not include changes in 6b5edec

> The page build failed for the `master` branch with the following error:
>  
> Unable to build page. Please try again later.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact/pages?repo_id=16789090&page_build_id=168669405

**Comment by chriscool** [comment]
I would try to add content step by step. It's inefficient, but it might help us understand what's going on.

**Comment by jnareb** [comment]
Now it compiled...

**Comment by chriscool** [comment]
@jnareb did you change anything?

Thanks anyway!

**Pull request merged**
