### PR TITLE
Tiny fixes to wording of General section

### PR DESCRIPTION
**Pull request by durdn**
I did a quick pass rewording a couple of paragraphs. Feel free to discard if you want to maintain a single consistent voice.

### CODE REVIEW

**Comment by durdn** [comment]
@gitster sorry about that, indeed my bad vim `gq` re-wrapping habit took over. I'll split the two actions next time.

**Comment by tfnico** [comment]
Out of curiosity, what is the general solution for that problem? Should one first check in bad line lengths while fixing wording, and thereafter correct line wrapping in a second commit?

**Comment by gitster** [comment]
@tfnico Yeah, if you really want to rewrap, then do the real fix as-is and then rewrap in a separate commit would be the way to go, as doing these in opposite order would not make much sense (the real fix likely will make the line length uneven again).

But we are dealing with markdown whose final rendering will wrap lines appropriately, so
not doing any rewrapping would be the way to go, IMNSHO ;-)

**Comment by peff** [comment]
Actually, markdown wrapping is not consistent from flavor to flavor. Some flavors will keep hard newlines inside a paragraph (and expect each paragraph to be on its own line). This is helpful for clueless folks pasting text into a browser input box, but I find it intensely irritating.

I noticed this when test-rendering #54 (i.e., the "view" button on GitHub), but it looks like there is hard-wrapping throughout the document as rendered by Jekyll (find the "Paraphrasing Junio" line, for example). You can replace the markdown renderer in Jekyll; I wouldn't be surprised if you can also tweak the wrapping behavior.

**Pull request merged**
