### PR TITLE
rn-110: Link to Boost Your Git DX update

### PR DESCRIPTION
**Pull request by adamchainz**

### CODE REVIEW

**Comment by chriscool** [comment]
Thanks Adam! I would be Ok to merge, but I prefer @jnareb to have the final say in the links (also called "Other News") section.

@jnareb please take a look.

**Comment by jnareb** [comment]
Looks good; I would add the following:

> This book was mentioned in [Git Rev News Edition #104](https://git.github.io/rev_news/2023/10/31/edition-104/).

**Comment by chriscool** [comment]
> Looks good; I would add the following:
>
> > This book was mentioned in [Git Rev News Edition #104](https://git.github.io/rev_news/2023/10/31/edition-104/).

Ok, let's just merge then and add what you suggest afterwards.

**Comment by chriscool** [comment]
@jnareb I just added what you suggest in b877a9b2b949f03ca03b8a6d32f21260a438931f.

**Comment by adamchainz** [comment]
Thanks! 🙏

**Pull request merged**
