### PR TITLE
Remove violent language; replace it with the desired action.

### PR DESCRIPTION
**Pull request by emmajane**
It is not necessary to ask people to beat software, when the desired outcome is actually
to have people test the software. Using clear, positive language will help reinforce the
friendly, helpful behaviour I experienced at Git Merge.

### CODE REVIEW

**Comment by tfnico** [comment]
Thanks Emma!

**Comment by emmajane** [comment]
Aha! I had misunderstood that it was a direct quote from the link. I agree that it should either be a direct quote, attributed; or a directive from the newsletter which uses "plain language". If I were sugarcoating it would look much different again. ;) I'm happy to submit a new PR, according to @gitster's preference (as the source of the quote, I think it makes sense to let the author choose).

**Comment by tfnico** [comment]
According to the comment here  https://github.com/git/git.github.io/commit/6269b5b2f9fc13eb529f1faf892868c1b1c8c9c7#commitcomment-10708448 I think everyone's happy now.

Next time I'll merge a bit less fast. But let me underline how I really appreciate Emma's initiative to help us here :)

**Comment by emmajane** [comment]
<3

Onwards! :)

**Pull request merged**
